// custom elements available in *.md to render in the prose (e.g. minim.md)

import { MdMarker, MdTex } from "../minim/web";
import { DarkModeToggle } from "./dark-mode-toggle";
import { MdCodec } from "./md-codec";
import { MdGroup } from "./md-group";
import { MdLubyTransform } from "./md-luby-transform";
import { MdQrtpHandshake } from "./md-qrtp-handshake";
import { MdQrtpProtocol } from "./md-qrtp-protocol";
import { MdQuote } from "./md-quote";
import { MdSyntax } from "./md-syntax";
import { MdAnchors } from "./optical-centering/md-anchors";
import { MdBboxHandles } from "./optical-centering/md-bbox-handles";
import { MdBehaviors } from "./optical-centering/md-behaviors";
import { MdBestFit } from "./optical-centering/md-best-fit";
import { MdBezierGestalt } from "./optical-centering/md-bezier-gestalt";
import { MdBoolBridges } from "./optical-centering/md-bool-bridges";
import { MdCancel } from "./optical-centering/md-cancel";
import { MdCanvasField } from "./optical-centering/md-canvas-field";
import { MdCentering } from "./optical-centering/md-centering";
import { MdChoreography } from "./optical-centering/md-choreography";
import { MdCircuit } from "./optical-centering/md-circuit";
import { MdClampQuantize } from "./optical-centering/md-clamp-quantize";
import { MdCloth } from "./optical-centering/md-cloth";
import { MdCode } from "./optical-centering/md-code";
import { MdConfocal } from "./optical-centering/md-confocal";
import { MdConformalDisc } from "./optical-centering/md-conformal-disc";
import { MdCoreactive } from "./optical-centering/md-coreactive";
import { MdDebugger } from "./optical-centering/md-debugger";
import { MdEquation } from "./optical-centering/md-equation";
import { MdFigure8 } from "./optical-centering/md-figure8";
import { MdGears } from "./optical-centering/md-gears";
import { MdGraph } from "./optical-centering/md-graph";
import { MdHandles } from "./optical-centering/md-handles";
import { MdIk } from "./optical-centering/md-ik";
import { MdIncidence } from "./optical-centering/md-incidence";
import { MdInvertible } from "./optical-centering/md-invertible";
import { MdLayoutDemo } from "./optical-centering/md-layout-demo";
import { MdLerps } from "./optical-centering/md-lerps";
import { MdLoop } from "./optical-centering/md-loop";
import { MdMirror } from "./optical-centering/md-mirror";
import { MdMix } from "./optical-centering/md-mix";
import { MdMorph } from "./optical-centering/md-morph";
import { MdMultitrack } from "./optical-centering/md-multitrack";
import { MdOrbits } from "./optical-centering/md-orbits";
import { MdOscillator } from "./optical-centering/md-oscillator";
import { MdParticles } from "./optical-centering/md-particles";
import { MdPropFlex } from "./optical-centering/md-prop-flex";
import { MdPropGeom } from "./optical-centering/md-prop-geom";
import { MdPropSudoku } from "./optical-centering/md-prop-sudoku";
import { MdPropTypes } from "./optical-centering/md-prop-types";
import { MdPulley } from "./optical-centering/md-pulley";
import { MdRand } from "./optical-centering/md-rand";
import { MdReact } from "./optical-centering/md-react";
import { MdRigidRope } from "./optical-centering/md-rigid-rope";
import { MdRigidStack } from "./optical-centering/md-rigid-stack";
import { MdRuntimeTests } from "./optical-centering/md-runtime-tests";
import { MdSketchpad } from "./optical-centering/md-sketchpad";
import { MdSketchpadLive } from "./optical-centering/md-sketchpad-live";
import { MdSliderCrank } from "./optical-centering/md-slider-crank";
import { MdSolarSystem } from "./optical-centering/md-solar-system";
import { MdStringPipeline } from "./optical-centering/md-string-pipeline";
import { MdTexDemo } from "./optical-centering/md-tex-demo";
import { MdTexLive } from "./optical-centering/md-tex-live";
import { MdTimelineEditor } from "./optical-centering/md-timeline-editor";
import { MdTrails } from "./optical-centering/md-trails";
import { MdTraitsCrossDomain } from "./optical-centering/md-traits-cross-domain";
import { MdTransitions } from "./optical-centering/md-transitions";
import { MdWaapiDemo } from "./optical-centering/md-waapi-demo";

DarkModeToggle.define();
MdQuote.define();
MdCodec.define();
MdLubyTransform.define();
MdQrtpHandshake.define();
MdGroup.define();
MdSyntax.define();
MdQrtpProtocol.define();
MdCentering.define();
MdCancel.define();
MdReact.define();
MdTransitions.define();
MdOrbits.define();
MdLayoutDemo.define();
MdTimelineEditor.define();
MdMultitrack.define();
MdCircuit.define();
MdRuntimeTests.define();
MdDebugger.define();
MdChoreography.define();
MdBehaviors.define();
MdBboxHandles.define();
MdBestFit.define();
MdBezierGestalt.define();
MdBoolBridges.define();
MdTraitsCrossDomain.define();
MdRand.define();
MdTexDemo.define();
MdTexLive.define();
MdWaapiDemo.define();
MdAnchors.define();
MdHandles.define();
MdInvertible.define();
MdMirror.define();
MdMix.define();
MdLerps.define();
MdMorph.define();
MdCanvasField.define();
MdClampQuantize.define();
MdOscillator.define();
MdTrails.define();
MdCode.define();
MdSolarSystem.define();
MdStringPipeline.define();
MdGears.define();
MdPulley.define();
MdIk.define();
MdConfocal.define();
MdConformalDisc.define();
MdSketchpad.define();
MdSketchpadLive.define();
MdCoreactive.define();
MdIncidence.define();
MdSliderCrank.define();
MdCloth.define();
MdParticles.define();
MdRigidStack.define();
MdRigidRope.define();
MdFigure8.define();
MdGraph.define();
MdEquation.define();
MdLoop.define();
MdPropFlex.define();
MdPropGeom.define();
MdPropSudoku.define();
MdPropTypes.define();
MdTex.define();
MdMarker.define();
