import { MdMarker, MdTex } from "../minim/web";
import { DarkModeToggle } from "./dark-mode-toggle";
import { MdCodec } from "./md-codec";
import { MdGroup } from "./md-group";
import { MdLubyTransform } from "./md-luby-transform";
import { MdQrtpHandshake } from "./md-qrtp-handshake";
import { MdQrtpProtocol } from "./md-qrtp-protocol";
import { MdQuote } from "./md-quote";
import { MdSyntax } from "./md-syntax";
import { MdAggregates } from "./optical-centering/md-aggregates";
import { MdAnchors } from "./optical-centering/md-anchors";
import { MdBehaviors } from "./optical-centering/md-behaviors";
import { MdCancel } from "./optical-centering/md-cancel";
import { MdCanvasField } from "./optical-centering/md-canvas-field";
import { MdCentering } from "./optical-centering/md-centering";
import { MdChoreography } from "./optical-centering/md-choreography";
import { MdCircuit } from "./optical-centering/md-circuit";
import { MdCode } from "./optical-centering/md-code";
import { MdColor } from "./optical-centering/md-color";
import { MdDebugger } from "./optical-centering/md-debugger";
import { MdGears } from "./optical-centering/md-gears";
import { MdHandles } from "./optical-centering/md-handles";
import { MdIk } from "./optical-centering/md-ik";
import { MdLayoutDemo } from "./optical-centering/md-layout-demo";
import { MdLerps } from "./optical-centering/md-lerps";
import { MdMirror } from "./optical-centering/md-mirror";
import { MdMorph } from "./optical-centering/md-morph";
import { MdMultitrack } from "./optical-centering/md-multitrack";
import { MdOrbits } from "./optical-centering/md-orbits";
import { MdOscillator } from "./optical-centering/md-oscillator";
import { MdPulley } from "./optical-centering/md-pulley";
import { MdRand } from "./optical-centering/md-rand";
import { MdReact } from "./optical-centering/md-react";
import { MdRuntimeTests } from "./optical-centering/md-runtime-tests";
import { MdSolarSystem } from "./optical-centering/md-solar-system";
import { MdTexCorrespond } from "./optical-centering/md-tex-correspond";
import { MdTexDemo } from "./optical-centering/md-tex-demo";
import { MdTexLive } from "./optical-centering/md-tex-live";
import { MdTexMatrix } from "./optical-centering/md-tex-matrix";
import { MdTexProse } from "./optical-centering/md-tex-prose";
import { MdTimelineEditor } from "./optical-centering/md-timeline-editor";
import { MdTrails } from "./optical-centering/md-trails";
import { MdTransitions } from "./optical-centering/md-transitions";
import { MdWaapiDemo } from "./optical-centering/md-waapi-demo";

DarkModeToggle.define();
MdQuote.define();
MdCodec.define();
MdLubyTransform.define();
MdQrtpHandshake.define();
MdGroup.define();
MdSyntax.define();
MdQrtpProtocol.define();
MdCentering.define();
MdCancel.define();
MdReact.define();
MdTransitions.define();
MdOrbits.define();
MdLayoutDemo.define();
MdTimelineEditor.define();
MdMultitrack.define();
MdCircuit.define();
MdRuntimeTests.define();
MdDebugger.define();
MdChoreography.define();
MdBehaviors.define();
MdAggregates.define();
MdRand.define();
MdTexDemo.define();
MdTexCorrespond.define();
MdTexMatrix.define();
MdTexLive.define();
MdWaapiDemo.define();
MdAnchors.define();
MdHandles.define();
MdMirror.define();
MdLerps.define();
MdMorph.define();
MdCanvasField.define();
MdTexProse.define();
MdOscillator.define();
MdTrails.define();
MdCode.define();
MdSolarSystem.define();
MdGears.define();
MdPulley.define();
MdIk.define();
MdColor.define();
MdTex.define();
MdMarker.define();
