import { DarkModeToggle } from "./dark-mode-toggle";
import { MdQuote } from "./md-quote";
import { MdCodec } from "./md-codec";
import { MdLubyTransform } from "./md-luby-transform";
import { MdQrtpHandshake } from "./md-qrtp-handshake";
import { MdGroup } from "./md-group";
import { MdSyntax } from "./md-syntax";
import { MdQrtpProtocol } from "./md-qrtp-protocol";
import { MdCentering } from "./optical-centering/md-centering";
import { MdCancel } from "./optical-centering/md-cancel";
import { MdReact } from "./optical-centering/md-react";
import { MdTransitions } from "./optical-centering/md-transitions";
import { MdOrbits } from "./optical-centering/md-orbits";
import { MdLayoutDemo } from "./optical-centering/md-layout-demo";
import { MdTimelineEditor } from "./optical-centering/md-timeline-editor";
import { MdMultitrack } from "./optical-centering/md-multitrack";
import { MdCircuit } from "./optical-centering/md-circuit";
import { MdRuntimeTests } from "./optical-centering/md-runtime-tests";
import { MdTraceDemo } from "./optical-centering/md-trace-demo";
import { MdChoreography } from "./optical-centering/md-choreography";
import { MdBehaviors } from "./optical-centering/md-behaviors";
import { MdAggregates } from "./optical-centering/md-aggregates";
import { MdRand } from "./optical-centering/md-rand";
import { MdClaimDemo } from "./optical-centering/md-claim-demo";
import { MdTexDemo } from "./optical-centering/md-tex-demo";
import { MdTexCorrespond } from "./optical-centering/md-tex-correspond";
import { MdTexMatrix } from "./optical-centering/md-tex-matrix";
import { MdTexLive } from "./optical-centering/md-tex-live";
import { MdWaapiDemo } from "./optical-centering/md-waapi-demo";
import { MdAnchors } from "./optical-centering/md-anchors";
import { MdHandles } from "./optical-centering/md-handles";
import { MdMirror } from "./optical-centering/md-mirror";

DarkModeToggle.define();
MdQuote.define();
MdCodec.define();
MdLubyTransform.define();
MdQrtpHandshake.define();
MdGroup.define();
MdSyntax.define();
MdQrtpProtocol.define();
MdCentering.define();
MdCancel.define();
MdReact.define();
MdTransitions.define();
MdOrbits.define();
MdLayoutDemo.define();
MdTimelineEditor.define();
MdMultitrack.define();
MdCircuit.define();
MdRuntimeTests.define();
MdTraceDemo.define();
MdChoreography.define();
MdBehaviors.define();
MdAggregates.define();
MdRand.define();
MdClaimDemo.define();
MdTexDemo.define();
MdTexCorrespond.define();
MdTexMatrix.define();
MdTexLive.define();
MdWaapiDemo.define();
MdAnchors.define();
MdHandles.define();
MdMirror.define();
